# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Plugin-RetrieveAll
version:      1.04
version_from: lib/Class/DBI/Plugin/RetrieveAll.pm
installdirs:  site
requires:
    Class::DBI:                    0.95

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
